import type { Metadata } from "next";
import "./globals.css";
import Clientside from "@/layouts/Clientside";
import ToastProvider from "@/provider/ToastProvider";
import Footer from "@/components/Footer";



export const metadata: Metadata = {
  title: "Arjayaprint",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <link
        rel="icon"
        href="/icon?<generated>"
        type="image/<generated>"
        sizes="<generated>"
      />
      </head>
      <body>
        <ToastProvider />
        <Clientside />
        {children}
        <Footer/>
      </body>
    </html>
  );
}
